# Generated by Django 6.0.2 on 2026-04-12 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_consulta_medico_alter_consulta_paciente_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='clinica',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__tipo': 'admin_clinica'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='crm',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='endereco',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('admin_clinica', 'Admin de Clínica'), ('medico', 'Medico'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
