# Generated by Django 6.0.2 on 2026-04-13 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_criada_em_consulta_status_consulta_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data', '-hora'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='clinica',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('admin_clinica', 'Admin de Clínica'), ('medico', 'Médico'), ('paciente', 'Paciente'), ('recepcionista', 'Recepcionista')], default='paciente', max_length=20),
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, default='')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinica_administrada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='clinica_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='consultas.clinica', verbose_name='Clínica'),
        ),
    ]
