# Generated by Django 6.0.2 on 2026-04-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_options_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='cnpj',
            new_name='NIF',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='cnpj',
            new_name='NIF',
        ),
    ]
