# Generated by Django 6.0.2 on 2026-04-24 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_rename_cnpj_clinica_nif_rename_cnpj_perfil_nif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, default='', help_text='Alergias a anestesia, medicamentos, látex, etc.')),
                ('medicamentos_em_uso', models.TextField(blank=True, default='', help_text='Medicamentos actuais que podem afectar o tratamento')),
                ('doencas_sistemicas', models.TextField(blank=True, default='', help_text='Ex: diabetes, hipertensão, cardiopatia, coagulopatia')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Notas livres do médico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('medico_preferencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_preferenciais', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoDentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta de rotina'), ('extracao', 'Extracção'), ('canal', 'Tratamento de canal'), ('ortodontia', 'Ortodontia'), ('implante', 'Implante'), ('limpeza', 'Limpeza / Profilaxia'), ('restauracao', 'Restauração / Obturação'), ('protese', 'Prótese'), ('cirurgia', 'Cirurgia oral'), ('outro', 'Outro')], default='consulta', max_length=20)),
                ('dente', models.CharField(blank=True, default='', help_text='Notação FDI — ex: 11, 36, 48', max_length=10)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimento_dentario', to='consultas.consulta')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='consultas.prontuario')),
            ],
            options={
                'verbose_name': 'Procedimento Dentário',
                'verbose_name_plural': 'Procedimentos Dentários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AnexoProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('raio_x_panoramico', 'Raio-X Panorâmico'), ('raio_x_apical', 'Raio-X Apical'), ('foto_clinica', 'Foto Clínica'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='prontuarios/%Y/%m/')),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_exame', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_adicionados', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='consultas.prontuario')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-data_exame'],
            },
        ),
    ]
