# Generated by Django 6.0.2 on 2026-04-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_prontuario_procedimentodentario_anexoprontuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartilhaProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], max_length=10)),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferência de Paciente'), ('segunda_opiniao', 'Segunda Opinião')], max_length=20)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aceite', 'Aceite'), ('recusado', 'Recusado'), ('concluido', 'Concluído')], default='pendente', max_length=10)),
                ('mensagem', models.TextField(blank=True, default='', help_text='Motivo do pedido / notas para a clínica destino')),
                ('resposta', models.TextField(blank=True, default='', help_text='Resposta da clínica destino ao aceitar ou recusar')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_recebidas', to='consultas.clinica')),
                ('clinica_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_enviadas', to='consultas.clinica')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('medico_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_recebidas', to=settings.AUTH_USER_MODEL)),
                ('medico_responsavel_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partilhas', to='consultas.prontuario')),
            ],
            options={
                'verbose_name': 'Partilha de Prontuário',
                'verbose_name_plural': 'Partilhas de Prontuário',
                'ordering': ['-criado_em'],
            },
        ),
    ]
