# Generated by Django 6.0.2 on 2026-05-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_partilhaprontuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partilhaprontuario',
            name='mensagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partilhaprontuario',
            name='resposta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='procedimentodentario',
            name='dente',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='alergias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='doencas_sistemicas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='medicamentos_em_uso',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('participantes', models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.AddField(
            model_name='partilhaprontuario',
            name='conversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partilhas_associadas', to='consultas.conversa'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='consultas.conversa')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
